package com.yizhaoqi.smartpai.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.yizhaoqi.smartpai.client.DeepSeekClient;
import com.yizhaoqi.smartpai.entity.ChatMessage;
import com.yizhaoqi.smartpai.entity.SearchResult;
import com.yizhaoqi.smartpai.util.PromptBuilder;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.stereotype.Service;
import org.springframework.web.socket.TextMessage;
import org.springframework.web.socket.WebSocketSession;

import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;

/**
 * 聊天处理服务
 * 负责处理WebSocket聊天消息和管理对话历史
 * 
 * @author Generated by Assistant
 */
@Service
public class ChatHandler {
    
    private static final Logger logger = LoggerFactory.getLogger(ChatHandler.class);
    private final RedisTemplate<String, String> redisTemplate;
    private final HybridSearchService searchService;
    private final DeepSeekClient deepSeekClient;
    private final ChatContextService contextService;
    private final ObjectMapper objectMapper;
    
    // 用于存储每个会话的完整响应
    private final Map<String, StringBuilder> responseBuilders = new ConcurrentHashMap<>();
    // 用于跟踪每个会话的响应完成状态
    private final Map<String, CompletableFuture<String>> responseFutures = new ConcurrentHashMap<>();
    // 停止标志
    private final Map<String, Boolean> stopFlags = new ConcurrentHashMap<>();
    // 会话ID映射：WebSocketSession.id -> 业务sessionId
    private final Map<String, String> sessionMapping = new ConcurrentHashMap<>();

    public ChatHandler(RedisTemplate<String, String> redisTemplate,
                      HybridSearchService searchService,
                      DeepSeekClient deepSeekClient,
                      ChatContextService contextService) {
        this.redisTemplate = redisTemplate;
        this.searchService = searchService;
        this.deepSeekClient = deepSeekClient;
        this.contextService = contextService;
        this.objectMapper = new ObjectMapper();
    }

    public void processMessage(String userId, String userMessage, WebSocketSession session) {
        logger.info("开始处理消息，用户ID: {}, WebSocket会话ID: {}", userId, session.getId());
        try {
            // 1. 获取或创建业务会话ID（用于上下文管理）
            String sessionId = getOrCreateSessionId(userId, session.getId());
            logger.info("业务会话ID: {}, 用户ID: {}", sessionId, userId);
            
            // 为当前会话创建响应构建器
            responseBuilders.put(session.getId(), new StringBuilder());
            // 创建一个CompletableFuture来跟踪响应完成状态
            CompletableFuture<String> responseFuture = new CompletableFuture<>();
            responseFutures.put(session.getId(), responseFuture);
            
            // 2. 获取或创建上下文，加载历史对话（最近10轮）
            com.yizhaoqi.smartpai.entity.ChatContext context = 
                contextService.getOrCreateContext(sessionId, userId);
            List<ChatMessage> chatHistory = context.getRecentHistory(10);
            List<Map<String, String>> history = PromptBuilder.buildHistoryMessages(chatHistory);
            logger.info("获取到 {} 条历史对话消息, sessionId={}, userId={}", history.size(), sessionId, userId);
            
            // 打印历史消息内容（调试）
            if (!chatHistory.isEmpty()) {
                for (int i = 0; i < chatHistory.size(); i++) {
                    ChatMessage msg = chatHistory.get(i);
                    logger.debug("历史消息[{}]: role={}, content={}", i, msg.getRole(), 
                        msg.getContent() != null && msg.getContent().length() > 50 
                            ? msg.getContent().substring(0, 50) + "..." 
                            : msg.getContent());
                }
            }
            
            // 3. 执行带权限过滤的混合搜索
            List<SearchResult> searchResults = searchService.searchWithPermission(userMessage, userId, 5);
            logger.debug("搜索结果数量: {}", searchResults.size());
            
            // 4. 构建RAG上下文
            String ragContext = buildContext(searchResults);
            
            // 5. 调用 DeepSeek API 并处理流式响应
            logger.info("调用DeepSeek API生成回复");
            // 保存最终会话ID用于后续保存消息
            final String finalSessionId = sessionId;
            final String finalUserMessage = userMessage;
            deepSeekClient.streamResponse(userMessage, ragContext, history, 
                chunk -> {
                    // 累积响应内容
                    StringBuilder responseBuilder = responseBuilders.get(session.getId());
                    if (responseBuilder != null) {
                        responseBuilder.append(chunk);
                    }
                    sendResponseChunk(session, chunk);
                },
                error -> {
                    // 处理错误并完成future
                    handleError(session, error);
                    // 发送响应完成通知（错误情况）
                    sendCompletionNotification(session);
                    responseFuture.completeExceptionally(error);
                    // 清理会话响应构建器
                    responseBuilders.remove(session.getId());
                    responseFutures.remove(session.getId());
                });
            
            // 6. 启动一个后台任务检查并标记响应完成
            new Thread(() -> {
                try {
                    Thread.sleep(3000);
                    
                    StringBuilder responseBuilder = responseBuilders.get(session.getId());
                    
                    if (responseBuilder != null) {
                        int lastLength = responseBuilder.length();
                        
                        Thread.sleep(2000);
                        
                        if (responseBuilder.length() == lastLength) {
                            responseFuture.complete(responseBuilder.toString());
                            logger.info("DeepSeek响应已完成，长度: {}", responseBuilder.length());
                            
                            sendCompletionNotification(session);
                            
                            // 更新对话历史（使用新的上下文服务）
                            String completeResponse = responseBuilder.toString();
                            contextService.addRound(finalSessionId, finalUserMessage, completeResponse);
                            logger.info("对话已保存 - 业务会话ID: {}", finalSessionId);
                            
                            responseBuilders.remove(session.getId());
                            responseFutures.remove(session.getId());
                            logger.info("消息处理完成，用户ID: {}", userId);
                        } else {
                            logger.debug("响应仍在继续，等待完成...");
                            for (int i = 0; i < 5; i++) {
                                Thread.sleep(5000);
                                if (responseBuilder != null) {
                                    lastLength = responseBuilder.length();
                                    Thread.sleep(2000);
                                    if (responseBuilder.length() == lastLength) {
                                        responseFuture.complete(responseBuilder.toString());
                                        
                                        sendCompletionNotification(session);
                                        
                                        String completeResponse = responseBuilder.toString();
                                        contextService.addRound(finalSessionId, finalUserMessage, completeResponse);
                                        logger.info("对话已保存 - 业务会话ID: {}", finalSessionId);
                                        
                                        responseBuilders.remove(session.getId());
                                        responseFutures.remove(session.getId());
                                        logger.info("消息处理完成，用户ID: {}", userId);
                                        return;
                                    }
                                }
                            }
                            
                            if (!responseFuture.isDone()) {
                                responseFuture.complete(responseBuilder.toString());
                                
                                sendCompletionNotification(session);
                                
                                String completeResponse = responseBuilder.toString();
                                contextService.addRound(finalSessionId, finalUserMessage, completeResponse);
                                logger.info("对话已保存 - 业务会话ID: {}", finalSessionId);
                                
                                responseBuilders.remove(session.getId());
                                responseFutures.remove(session.getId());
                                logger.info("消息处理强制完成，用户ID: {}", userId);
                            }
                        }
                    } else {
                        logger.warn("响应构建器为空，可能出现了错误，会话ID: {}", session.getId());
                        RuntimeException exception = new RuntimeException("响应构建器为空");
                        responseFuture.completeExceptionally(exception);
                        handleError(session, exception);
                    }
                } catch (Exception e) {
                    logger.error("检查响应完成时出错: {}", e.getMessage(), e);
                    responseFuture.completeExceptionally(e);
                    responseBuilders.remove(session.getId());
                    responseFutures.remove(session.getId());
                }
            }).start();
            
        } catch (Exception e) {
            logger.error("处理消息错误: {}", e.getMessage(), e);
            handleError(session, e);
            responseBuilders.remove(session.getId());
            CompletableFuture<String> future = responseFutures.remove(session.getId());
            if (future != null && !future.isDone()) {
                future.completeExceptionally(e);
            }
        }
    }

    /**
     * 获取或创建业务会话ID
     * 同一用户的WebSocket连接使用相同的业务会话ID
     */
    private String getOrCreateSessionId(String userId, String wsSessionId) {
        String sessionId = "session:" + userId;
        sessionMapping.put(wsSessionId, sessionId);
        return sessionId;
    }

    /**
     * 获取WebSocket会话对应的业务会话ID
     */
    public String getSessionId(String wsSessionId) {
        return sessionMapping.get(wsSessionId);
    }

    /**
     * 清除会话映射
     */
    public void clearSession(String wsSessionId) {
        sessionMapping.remove(wsSessionId);
        responseBuilders.remove(wsSessionId);
        responseFutures.remove(wsSessionId);
        stopFlags.remove(wsSessionId);
    }

    private String buildContext(List<SearchResult> searchResults) {
        if (searchResults == null || searchResults.isEmpty()) {
            return "";
        }

        final int MAX_SNIPPET_LEN = 300;
        StringBuilder context = new StringBuilder();
        for (int i = 0; i < searchResults.size(); i++) {
            SearchResult result = searchResults.get(i);
            String snippet = result.getTextContent();
            if (snippet != null && snippet.length() > MAX_SNIPPET_LEN) {
                snippet = snippet.substring(0, MAX_SNIPPET_LEN) + "…";
            }
            String fileLabel = result.getFileName() != null ? result.getFileName() : "unknown";
            context.append(String.format("[%d] (%s) %s\n", i + 1, fileLabel, snippet));
        }
        return context.toString();
    }

    private void sendResponseChunk(WebSocketSession session, String chunk) {
        try {
            if (Boolean.TRUE.equals(stopFlags.get(session.getId()))) {
                logger.debug("检测到停止标志，跳过发送响应块");
                return;
            }
            
            Map<String, String> chunkResponse = Map.of("chunk", chunk);
            String jsonChunk = objectMapper.writeValueAsString(chunkResponse);
            session.sendMessage(new TextMessage(jsonChunk));
        } catch (Exception e) {
            logger.error("发送响应块失败: {}", e.getMessage(), e);
        }
    }

    private void sendCompletionNotification(WebSocketSession session) {
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> notification = Map.of(
                "type", "completion",
                "status", "finished", 
                "message", "响应已完成",
                "timestamp", currentTime,
                "date", java.time.LocalDateTime.now().toString()
            );
            String notificationJson = objectMapper.writeValueAsString(notification);
            session.sendMessage(new TextMessage(notificationJson));
            logger.info("已发送响应完成通知到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送完成通知失败: {}", e.getMessage(), e);
        }
    }

    private void handleError(WebSocketSession session, Throwable error) {
        logger.error("AI服务错误: {}", error.getMessage(), error);
        try {
            Map<String, String> errorResponse = Map.of("error", "AI服务暂时不可用，请稍后重试");
            String errorJson = objectMapper.writeValueAsString(errorResponse);
            session.sendMessage(new TextMessage(errorJson));
        } catch (Exception e) {
            logger.error("发送错误消息失败: {}", e.getMessage(), e);
        }
    }

    /**
     * 停止响应 
     */
    public void stopResponse(String userId, WebSocketSession session) {
        String sessionId = session.getId();
        logger.info("收到停止请求，用户ID: {}, 会话ID: {}", userId, sessionId);
        
        stopFlags.put(sessionId, true);
        
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> response = Map.of(
                "type", "stop", 
                "message", "响应已停止",
                "timestamp", currentTime,
                "date", java.time.Instant.ofEpochMilli(currentTime).toString()
            );
            String stopJson = objectMapper.writeValueAsString(response);
            session.sendMessage(new TextMessage(stopJson));
            logger.info("已发送停止确认，会话ID: {}", sessionId);
        } catch (Exception e) {
            logger.error("发送停止确认失败: {}", e.getMessage(), e);
        }
        
        new Thread(() -> {
            try {
                Thread.sleep(2000);
                stopFlags.remove(sessionId);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }).start();
    }
}
